#  menu items
[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"

#[[main]]
#  name = "Docs"
#  weight = 2
#  url = "docs/"


[[main]]
  name = "About"
  weight = 2
  url = "about/"


# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"